services:
  unifi-apclients-mqtt:
    image: ghcr.io/ryther/unifi-apclients-mqtt:latest
    env_file:
      - .env
    environment:
      UNIFI_PASSWORD_FILE: /run/secrets/unifi_password
      MQTT_PASSWORD_FILE: /run/secrets/mqtt_password
    secrets:
      - unifi_password
      - mqtt_password
    restart: unless-stopped

secrets:
  unifi_password:
    file: ./secrets/unifi_password
  mqtt_password:
    file: ./secrets/mqtt_password
