sonar.organization=ryther
sonar.projectKey=unifi-apclients-mqtt
sonar.projectName=UniFi AP Clients MQTT
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**
sonar.exclusions=target/**,site/**
sonar.sourceEncoding=UTF-8
sonar.rust.clippy.enabled=false
sonar.rust.clippyReport.reportPaths=clippy-report.json
sonar.rust.lcov.reportPaths=lcov.info
